name: "CI (lite): dependencies"

on:
  workflow_dispatch:
  push:
    branches: 
      - dependencies
  pull_request:
    branches: 
      - dependencies

permissions:
  contents: read
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  checks:
    uses: ./.github/workflows/checks.yml

  test:
    needs: checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: Swatinem/rust-cache@v2
      - run: cargo test --all-features
        