name: "CI (lite): dependencies"

on:
  workflow_dispatch:
  push:
    branches:
      - dependencies
  pull_request:
    branches:
      - dependencies

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  checks:
    uses: ./.github/workflows/checks.yml
